package projek;

import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;


public class desain extends javax.swing.JFrame {

    public desain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NP = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        NH = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        V = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        nomorHp = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Varian = new javax.swing.JComboBox<>();
        tb_simpan = new javax.swing.JButton();
        tb_edit = new javax.swing.JButton();
        tb_hapus = new javax.swing.JButton();
        tb_batal = new javax.swing.JButton();
        Cari = new javax.swing.JButton();
        isiCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noPesanan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Pemesanan");

        NP.setText("Jumlah");

        N.setText("Nama");

        NH.setText("Nomor Hp");

        A.setText("Alamat");

        V.setText("Varian Rasa");

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        Varian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "keju", "coklat", "melon", "blueberry", "strowberry", "kacang", " " }));

        tb_simpan.setText("Simpan");
        tb_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_simpanActionPerformed(evt);
            }
        });

        tb_edit.setText("Edit");
        tb_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_editActionPerformed(evt);
            }
        });

        tb_hapus.setText("Hapus");
        tb_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hapusActionPerformed(evt);
            }
        });

        tb_batal.setText("batal");
        tb_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_batalActionPerformed(evt);
            }
        });

        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel2.setText("Nama");

        jLabel3.setText("No urutan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(isiCari, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Cari))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(NP)
                                                .addComponent(N)
                                                .addComponent(jLabel3))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Nama)
                                                .addComponent(jumlah)
                                                .addComponent(noPesanan)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(NH)
                                                .addComponent(A)
                                                .addComponent(V))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(tb_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tb_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tb_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(nomorHp)
                                                .addComponent(Alamat)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Varian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addGap(18, 18, 18)
                                    .addComponent(tb_hapus))))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N)
                    .addComponent(tb_hapus))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NH)
                    .addComponent(nomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(V)
                    .addComponent(Varian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_simpan)
                    .addComponent(tb_edit)
                    .addComponent(tb_batal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isiCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cari)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void tb_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_simpanActionPerformed
        try {
    String sql = "INSERT INTO pembeli (id_pembeli, jumlah, nama_pembeli, no_telp, alamat, varian) VALUES (?, ?, ?, ?, ?, ?)";
    java.sql.Connection conn = (java.sql.Connection) projek.koneksi.koneksiDB();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, noPesanan.getText());
    pst.setString(2, jumlah.getText());
    pst.setString(3, Nama.getText());
    pst.setString(4, nomorHp.getText());
    pst.setString(5, Alamat.getText());
    pst.setString(6, Varian.getSelectedItem().toString());

    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
    tampil_data();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal di simpan: " + e.getMessage());
}
        
    }//GEN-LAST:event_tb_simpanActionPerformed

    private void tb_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hapusActionPerformed
        // TODO add your handling code here:
        try {
    java.sql.Connection conn = (java.sql.Connection) projek.koneksi.koneksiDB();
    String sql = "DELETE FROM pembeli WHERE nama_pembeli = ?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, Nama.getText()); // Menggunakan nama pembeli untuk menghapus

    int result = pst.executeUpdate();
    if (result > 0) {
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        tampil_data();
    } else {
        JOptionPane.showMessageDialog(null, "Data dengan nama " + Nama.getText() + " tidak ditemukan");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal: " + e.getMessage());
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_tb_hapusActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
       try {
        java.sql.Connection conn = (java.sql.Connection) projek.koneksi.koneksiDB();
        String sql = "Select * from pembeli where id_pembeli=? or nama_pembeli=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, isiCari.getText());
        pst.setString(2, isiCari.getText());
        ResultSet rs = pst.executeQuery();

        if (rs.next()){
            noPesanan.setText(rs.getString("id_pembeli"));
            jumlah.setText(rs.getString("jumlah"));
            Nama.setText(rs.getString("nama_pembeli"));
            nomorHp.setText(rs.getString("no_telp"));
            Alamat.setText(rs.getString("alamat"));
            Varian.setSelectedItem(rs.getString("varian"));
            JOptionPane.showMessageDialog(null, "Data " + isiCari.getText() + " ditemukan ");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Pencarian data gagal: " + e.getMessage());
    }
    isiCari.requestFocus();
    }//GEN-LAST:event_CariActionPerformed

    private void tb_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_batalActionPerformed
        // TODO add your handling code here:     
    noPesanan.setText("");
    jumlah.setText("");
    Nama.setText("");
    nomorHp.setText("");
    Alamat.setText("");
    Varian.setSelectedItem("");
    noPesanan.requestFocus();
    }//GEN-LAST:event_tb_batalActionPerformed

    private void tb_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_editActionPerformed
        // TODO add your handling code here:                                    
    try {
        java.sql.Connection conn = (java.sql.Connection) projek.koneksi.koneksiDB();
        String sql = "UPDATE pembeli SET jumlah=?, no_telp=?, alamat=?, varian=? WHERE nama_pembeli=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        //pst.setString(1, noPesanan.getText());
        pst.setString(1, jumlah.getText());
        pst.setString(2, nomorHp.getText());
        pst.setString(3, Alamat.getText());
        pst.setString(4, Varian.getSelectedItem().toString());
        pst.setString(5, Nama.getText()); // Berdasarkan nama_pembeli

        int result = pst.executeUpdate();
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
            tampil_data();
        } else {
            JOptionPane.showMessageDialog(null, "Data dengan nama " + Nama.getText() + " tidak ditemukan");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Proses pengeditan gagal: " + e.getMessage());
        System.out.println(e.getMessage());
    }

    }//GEN-LAST:event_tb_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desain().setVisible(true);
            }
        });
    }
    
   public void tampil_data() {
    DefaultTableModel model = (DefaultTableModel) tabel.getModel();
    model.setRowCount(0); // Menghapus semua baris di model tabel sebelum menambahkan data baru

    // Define the new column headers
    String[] columnHeaders = {"no_Pesanan", "jumlah", "nama", "no_telp", "alamat", "varian"};

    // Set the new column headers to the table model
    model.setColumnIdentifiers(columnHeaders);

    try {
        java.sql.Connection conn = (java.sql.Connection) projek.koneksi.koneksiDB();
        String sql = "SELECT * FROM pembeli"; // Perhatikan perbaikan penulisan SQL
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pembeli"),
                rs.getString("jumlah"), // Sesuaikan dengan nama kolom pada tabel database
                rs.getString("nama_pembeli"),
                rs.getString("no_telp"),
                rs.getString("alamat"),
                rs.getString("varian")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mengambil data: " + e.getMessage());
    }
}






    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JTextField Alamat;
    private javax.swing.JButton Cari;
    private javax.swing.JLabel N;
    private javax.swing.JLabel NH;
    private javax.swing.JLabel NP;
    private javax.swing.JTextField Nama;
    private javax.swing.JLabel V;
    private javax.swing.JComboBox<String> Varian;
    private javax.swing.JTextField isiCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField noPesanan;
    private javax.swing.JTextField nomorHp;
    protected javax.swing.JTable tabel;
    private javax.swing.JButton tb_batal;
    private javax.swing.JButton tb_edit;
    private javax.swing.JButton tb_hapus;
    private javax.swing.JButton tb_simpan;
    // End of variables declaration//GEN-END:variables
}
